---

- name: ELASTICSEARCH | add elasticsearch repo key
  rpm_key: key="http://packages.elasticsearch.org/GPG-KEY-elasticsearch" state=present
  tags: pkg

- name: ELASTICSEARCH | enable repository
  template: src=elasticsearch_repo.j2 dest=/etc/yum.repos.d/elasticsearch.repo
  tags: pkg

- name: ELASTICSEARCH | install 
  yum: name={{ item }} state=latest
  with_items:
   - elasticsearch
  notify:
   - restart elasticsearch
   tags: pkg

- name: ELASTICSEARCH | mkdir config folder
  file: path={{ elasticsearch_conf_dir }} state=directory owner=root group=root mode=0644
  tags: elasticsearch

- name: ELASTICSEARCH | configuration
  template: src=elasticsearch.yml.j2 dest={{ elasticsearch_conf_dir }}/{{ elasticsearch_conf_file }} owner=root group=root mode=0644
  notify:
   - restart elasticsearch
   tags: elasticsearch
 
